#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 01, 2021 08:05:59 PM EEST  platform: Windows NT
from PIL import ImageTk,Image
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import InteractionWithWnBuddiesGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = InteractionBuddiesToplevel (root)
    InteractionWithWnBuddiesGUI_support.init(root, top)
    root.mainloop()

w = None
def create_InteractionBuddiesToplevel(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_InteractionBuddiesToplevel(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = InteractionBuddiesToplevel (w)
    InteractionWithWnBuddiesGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_InteractionBuddiesToplevel():
    global w
    w.destroy()
    w = None

class InteractionBuddiesToplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(148, 1)
        top.maxsize(4804, 1325)
        top.resizable(1,  1)
        top.title("Menu")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.MyPictureCanvas = tk.Canvas(top)
        self.MyPictureCanvas.place(relx=0.35, rely=0.133, relheight=0.284
                , relwidth=0.213)
        self.MyPictureCanvas.configure(background="#d9d9d9")
        self.MyPictureCanvas.configure(borderwidth="2")
        self.MyPictureCanvas.configure(highlightbackground="#d9d9d9")
        self.MyPictureCanvas.configure(highlightcolor="black")
        self.MyPictureCanvas.configure(insertbackground="black")
        self.MyPictureCanvas.configure(relief="ridge")
        self.MyPictureCanvas.configure(selectbackground="blue")
        self.MyPictureCanvas.configure(selectforeground="white")

        img=Image.open('avatar.png')
        self.MyPictureCanvas.image=ImageTk.PhotoImage(img)
        self.MyPictureCanvas.create_image(0,0,image=self.MyPictureCanvas.image,anchor='nw')

        

        self.SearchBuddyButton = tk.Button(top)
        self.SearchBuddyButton.place(relx=0.333, rely=0.622, height=33
                , width=156)
        self.SearchBuddyButton.configure(activebackground="#ececec")
        self.SearchBuddyButton.configure(activeforeground="#000000")
        self.SearchBuddyButton.configure(background="#d9d9d9")
        self.SearchBuddyButton.configure(disabledforeground="#a3a3a3")
        self.SearchBuddyButton.configure(foreground="#000000")
        self.SearchBuddyButton.configure(highlightbackground="#d9d9d9")
        self.SearchBuddyButton.configure(highlightcolor="black")
        self.SearchBuddyButton.configure(pady="0")
        self.SearchBuddyButton.configure(text='''Search Whatnau Buddy''')

        self.PromoteEventToBuddyButton = tk.Button(top)
        self.PromoteEventToBuddyButton.place(relx=0.283, rely=0.733, height=33
                , width=226)
        self.PromoteEventToBuddyButton.configure(activebackground="#ececec")
        self.PromoteEventToBuddyButton.configure(activeforeground="#000000")
        self.PromoteEventToBuddyButton.configure(background="#d9d9d9")
        self.PromoteEventToBuddyButton.configure(disabledforeground="#a3a3a3")
        self.PromoteEventToBuddyButton.configure(foreground="#000000")
        self.PromoteEventToBuddyButton.configure(highlightbackground="#d9d9d9")
        self.PromoteEventToBuddyButton.configure(highlightcolor="black")
        self.PromoteEventToBuddyButton.configure(pady="0")
        self.PromoteEventToBuddyButton.configure(text='''Promote event to Wn Buddy''')

        self.MyBuddiesButton = tk.Button(top)
        self.MyBuddiesButton.place(relx=0.35, rely=0.867, height=33, width=146)
        self.MyBuddiesButton.configure(activebackground="#ececec")
        self.MyBuddiesButton.configure(activeforeground="#000000")
        self.MyBuddiesButton.configure(background="#0000ff")
        self.MyBuddiesButton.configure(disabledforeground="#a3a3a3")
        self.MyBuddiesButton.configure(foreground="#ffffff")
        self.MyBuddiesButton.configure(highlightbackground="#d9d9d9")
        self.MyBuddiesButton.configure(highlightcolor="black")
        self.MyBuddiesButton.configure(pady="0")
        self.MyBuddiesButton.configure(text='''My Buddies''')

        self.ShareTaskButton = tk.Button(top)
        self.ShareTaskButton.place(relx=0.4, rely=0.511, height=33, width=86)
        self.ShareTaskButton.configure(activebackground="#ececec")
        self.ShareTaskButton.configure(activeforeground="#000000")
        self.ShareTaskButton.configure(background="#d9d9d9")
        self.ShareTaskButton.configure(disabledforeground="#a3a3a3")
        self.ShareTaskButton.configure(foreground="#000000")
        self.ShareTaskButton.configure(highlightbackground="#d9d9d9")
        self.ShareTaskButton.configure(highlightcolor="black")
        self.ShareTaskButton.configure(pady="0")
        self.ShareTaskButton.configure(text='''Share Task''')

if __name__ == '__main__':
    vp_start_gui()





