#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 08, 2021 01:59:10 PM EEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import LoginPage_support
global password_value
def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = LoginToplevel (root)
    LoginPage_support.init(root, top)
    root.mainloop()

w = None
def create_LoginToplevel(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_LoginToplevel(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = LoginToplevel (w)
    LoginPage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_LoginToplevel():
    global w
    w.destroy()
    w = None



    
    

class LoginToplevel:
    
        
    
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(148, 1)
        top.maxsize(4804, 1325)
        top.resizable(1,  1)
        top.title("Whatnau Login Page")
        top.configure(background="#d9d9d9")

        

        def get_Username():
            global user
            user=self.UsernameEntry.get()
            return user


        self.UsernameEntry = tk.Entry(top)
        self.UsernameEntry.place(relx=0.4, rely=0.244, height=24, relwidth=0.273)

        self.UsernameEntry.configure(background="white")
        self.UsernameEntry.configure(disabledforeground="#a3a3a3")
        self.UsernameEntry.configure(font="TkFixedFont")
        self.UsernameEntry.configure(foreground="#000000")
        self.UsernameEntry.configure(insertbackground="black")

        self.PasswordEntry = tk.Entry(top,show='*')
        self.PasswordEntry.place(relx=0.4, rely=0.378, height=24, relwidth=0.273)

        self.PasswordEntry.configure(background="white")
        self.PasswordEntry.configure(disabledforeground="#a3a3a3")
        self.PasswordEntry.configure(font="TkFixedFont")
        self.PasswordEntry.configure(foreground="#000000")
        self.PasswordEntry.configure(insertbackground="black")

        self.CreateAccountButton = tk.Button(top)
        self.CreateAccountButton.place(relx=0.033, rely=0.044, height=33
                , width=126)
        self.CreateAccountButton.configure(activebackground="#ececec")
        self.CreateAccountButton.configure(activeforeground="#000000")
        self.CreateAccountButton.configure(background="#d9d9d9")
        self.CreateAccountButton.configure(disabledforeground="#a3a3a3")
        self.CreateAccountButton.configure(foreground="#000000")
        self.CreateAccountButton.configure(highlightbackground="#d9d9d9")
        self.CreateAccountButton.configure(highlightcolor="black")
        self.CreateAccountButton.configure(pady="0")
        self.CreateAccountButton.configure(text='''Create Account''')
##########################33 Na ftiaksw th BASH ####################3333
        def check_User(): 
            password_value=self.PasswordEntry.get()
            usr_value=self.UsernameEntry.get()
            
            if (password_value=='hello') and (usr_value=='mar'):
                print("All good")
                import OrganiserGUI as orgGUI
                try:
                    import Tkinter as tk
                except ImportError:
                    import tkinter as tk

                from PIL import ImageTk,Image
                #r=tk.Toplevel()

                root=tk.Toplevel()
                p=orgGUI.OrganiserToplevel1(root)
                root.mainloop()
                
                
            else:
                print("NOOOOOO")

            
            
 #############################################################           
        self.LoginButton = tk.Button(top,command=check_User)
        self.LoginButton.place(relx=0.433, rely=0.711, height=33, width=56)
        self.LoginButton.configure(activebackground="#ececec")
        self.LoginButton.configure(activeforeground="#000000")
        self.LoginButton.configure(background="#d9d9d9")
        self.LoginButton.configure(disabledforeground="#a3a3a3")
        self.LoginButton.configure(foreground="#000000")
        self.LoginButton.configure(highlightbackground="#d9d9d9")
        self.LoginButton.configure(highlightcolor="black")
        self.LoginButton.configure(pady="0")
        self.LoginButton.configure(text='''Login''')

        self.UsernameLabel = tk.Label(top)
        self.UsernameLabel.place(relx=0.233, rely=0.244, height=26, width=72)
        self.UsernameLabel.configure(background="#d9d9d9")
        self.UsernameLabel.configure(disabledforeground="#a3a3a3")
        self.UsernameLabel.configure(foreground="#000000")
        self.UsernameLabel.configure(text='''Username''')

        self.PasswordLabel = tk.Label(top)
        self.PasswordLabel.place(relx=0.233, rely=0.378, height=26, width=72)
        self.PasswordLabel.configure(background="#d9d9d9")
        self.PasswordLabel.configure(disabledforeground="#a3a3a3")
        self.PasswordLabel.configure(foreground="#000000")
        self.PasswordLabel.configure(text='''Password''')

        

if __name__ == '__main__':
    vp_start_gui()





