#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 08, 2021 10:09:57 PM EEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import OrganiserGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = OrganiserToplevel1 (root)
    OrganiserGUI_support.init(root, top)
    root.mainloop()

w = None
def create_OrganiserToplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_OrganiserToplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = OrganiserToplevel1 (w)
    OrganiserGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_OrganiserToplevel1():
    global w
    w.destroy()
    w = None

class OrganiserToplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+733+448")
        top.minsize(148, 1)
        top.maxsize(4804, 1325)
        top.resizable(1,  1)
        top.title("My Event")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.LocationCanvas = tk.Canvas(top)
        self.LocationCanvas.place(relx=0.7, rely=0.111, relheight=0.284
                , relwidth=0.213)
        self.LocationCanvas.configure(background="#d9d9d9")
        self.LocationCanvas.configure(borderwidth="2")
        self.LocationCanvas.configure(highlightbackground="#d9d9d9")
        self.LocationCanvas.configure(highlightcolor="black")
        self.LocationCanvas.configure(insertbackground="black")
        self.LocationCanvas.configure(relief="groove")
        self.LocationCanvas.configure(selectbackground="#0000ffffffff")
        self.LocationCanvas.configure(selectforeground="white")

        self.TicketValueLabel1 = tk.Label(top)
        self.TicketValueLabel1.place(relx=0.0, rely=0.333, height=26, width=92)
        self.TicketValueLabel1.configure(activebackground="#f9f9f9")
        self.TicketValueLabel1.configure(activeforeground="black")
        self.TicketValueLabel1.configure(background="#d9d9d9")
        self.TicketValueLabel1.configure(disabledforeground="#a3a3a3")
        self.TicketValueLabel1.configure(foreground="#000000")
        self.TicketValueLabel1.configure(highlightbackground="#d9d9d9")
        self.TicketValueLabel1.configure(highlightcolor="black")
        self.TicketValueLabel1.configure(text='''Ticket Value''')

        self.EventURLLabel = tk.Label(top)
        self.EventURLLabel.place(relx=0.0, rely=0.489, height=26, width=92)
        self.EventURLLabel.configure(activebackground="#f9f9f9")
        self.EventURLLabel.configure(activeforeground="black")
        self.EventURLLabel.configure(background="#d9d9d9")
        self.EventURLLabel.configure(disabledforeground="#a3a3a3")
        self.EventURLLabel.configure(foreground="#000000")
        self.EventURLLabel.configure(highlightbackground="#d9d9d9")
        self.EventURLLabel.configure(highlightcolor="black")
        self.EventURLLabel.configure(text='''Event's URL''')

        self.EventDateLabel = tk.Label(top)
        self.EventDateLabel.place(relx=0.0, rely=0.6, height=26, width=92)
        self.EventDateLabel.configure(activebackground="#f9f9f9")
        self.EventDateLabel.configure(activeforeground="black")
        self.EventDateLabel.configure(background="#d9d9d9")
        self.EventDateLabel.configure(disabledforeground="#a3a3a3")
        self.EventDateLabel.configure(foreground="#000000")
        self.EventDateLabel.configure(highlightbackground="#d9d9d9")
        self.EventDateLabel.configure(highlightcolor="black")
        self.EventDateLabel.configure(text='''Event's date''')

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.117, rely=0.756, relheight=0.218
                , relwidth=0.282)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(foreground="black")
        self.Scrolledtext1.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext1.configure(highlightcolor="black")
        self.Scrolledtext1.configure(insertbackground="black")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="blue")
        self.Scrolledtext1.configure(selectforeground="white")
        self.Scrolledtext1.configure(wrap="none")

        self.LocationLabel = tk.Label(top)
        self.LocationLabel.place(relx=0.0, rely=0.222, height=26, width=62)
        self.LocationLabel.configure(activebackground="#f9f9f9")
        self.LocationLabel.configure(activeforeground="black")
        self.LocationLabel.configure(background="#d9d9d9")
        self.LocationLabel.configure(disabledforeground="#a3a3a3")
        self.LocationLabel.configure(foreground="#000000")
        self.LocationLabel.configure(highlightbackground="#d9d9d9")
        self.LocationLabel.configure(highlightcolor="black")
        self.LocationLabel.configure(text='''Location''')

        self.LocationEntry = tk.Entry(top)
        self.LocationEntry.place(relx=0.183, rely=0.222, height=24
                , relwidth=0.223)
        self.LocationEntry.configure(background="white")
        self.LocationEntry.configure(disabledforeground="#a3a3a3")
        self.LocationEntry.configure(font="TkFixedFont")
        self.LocationEntry.configure(foreground="#000000")
        self.LocationEntry.configure(highlightbackground="#d9d9d9")
        self.LocationEntry.configure(highlightcolor="black")
        self.LocationEntry.configure(insertbackground="black")
        self.LocationEntry.configure(selectbackground="blue")
        self.LocationEntry.configure(selectforeground="white")

        self.ConfirmLocationButton = tk.Button(top)
        self.ConfirmLocationButton.place(relx=0.633, rely=0.622, height=93
                , width=156)
        self.ConfirmLocationButton.configure(activebackground="#ececec")
        self.ConfirmLocationButton.configure(activeforeground="#000000")
        self.ConfirmLocationButton.configure(background="#6d73da")
        self.ConfirmLocationButton.configure(disabledforeground="#a3a3a3")
        self.ConfirmLocationButton.configure(foreground="#ffffff")
        self.ConfirmLocationButton.configure(highlightbackground="#d9d9d9")
        self.ConfirmLocationButton.configure(highlightcolor="black")
        self.ConfirmLocationButton.configure(pady="0")
        self.ConfirmLocationButton.configure(text='''Confirm-upload event''')

        self.eTicketButton1 = tk.Button(top)
        self.eTicketButton1.place(relx=0.533, rely=0.333, height=33, width=59)
        self.eTicketButton1.configure(activebackground="#ececec")
        self.eTicketButton1.configure(activeforeground="#000000")
        self.eTicketButton1.configure(background="#00ff00")
        self.eTicketButton1.configure(disabledforeground="#a3a3a3")
        self.eTicketButton1.configure(foreground="#000000")
        self.eTicketButton1.configure(highlightbackground="#d9d9d9")
        self.eTicketButton1.configure(highlightcolor="black")
        self.eTicketButton1.configure(pady="0")
        self.eTicketButton1.configure(text='''eTicket''')

        self.EventURLEntry = tk.Entry(top)
        self.EventURLEntry.place(relx=0.183, rely=0.489, height=24
                , relwidth=0.173)
        self.EventURLEntry.configure(background="white")
        self.EventURLEntry.configure(disabledforeground="#a3a3a3")
        self.EventURLEntry.configure(font="TkFixedFont")
        self.EventURLEntry.configure(foreground="#000000")
        self.EventURLEntry.configure(highlightbackground="#d9d9d9")
        self.EventURLEntry.configure(highlightcolor="black")
        self.EventURLEntry.configure(insertbackground="black")
        self.EventURLEntry.configure(selectbackground="blue")
        self.EventURLEntry.configure(selectforeground="white")

        self.EventsDateEntry = tk.Entry(top)
        self.EventsDateEntry.place(relx=0.183, rely=0.6, height=24
                , relwidth=0.173)
        self.EventsDateEntry.configure(background="white")
        self.EventsDateEntry.configure(disabledforeground="#a3a3a3")
        self.EventsDateEntry.configure(font="TkFixedFont")
        self.EventsDateEntry.configure(foreground="#000000")
        self.EventsDateEntry.configure(highlightbackground="#d9d9d9")
        self.EventsDateEntry.configure(highlightcolor="black")
        self.EventsDateEntry.configure(insertbackground="black")
        self.EventsDateEntry.configure(selectbackground="blue")
        self.EventsDateEntry.configure(selectforeground="white")

        self.BusinessPhoneEntry = tk.Entry(top)
        self.BusinessPhoneEntry.place(relx=0.683, rely=0.889, height=24
                , relwidth=0.173)
        self.BusinessPhoneEntry.configure(background="white")
        self.BusinessPhoneEntry.configure(disabledforeground="#a3a3a3")
        self.BusinessPhoneEntry.configure(font="TkFixedFont")
        self.BusinessPhoneEntry.configure(foreground="#000000")
        self.BusinessPhoneEntry.configure(highlightbackground="#d9d9d9")
        self.BusinessPhoneEntry.configure(highlightcolor="black")
        self.BusinessPhoneEntry.configure(insertbackground="black")
        self.BusinessPhoneEntry.configure(selectbackground="blue")
        self.BusinessPhoneEntry.configure(selectforeground="white")

        self.EventInfoLabel = tk.Label(top)
        self.EventInfoLabel.place(relx=0.167, rely=0.689, height=26, width=102)
        self.EventInfoLabel.configure(activebackground="#f9f9f9")
        self.EventInfoLabel.configure(activeforeground="black")
        self.EventInfoLabel.configure(background="#d9d9d9")
        self.EventInfoLabel.configure(disabledforeground="#a3a3a3")
        self.EventInfoLabel.configure(foreground="#000000")
        self.EventInfoLabel.configure(highlightbackground="#d9d9d9")
        self.EventInfoLabel.configure(highlightcolor="black")
        self.EventInfoLabel.configure(text='''Event's Info''')

        self.BusinessPhoneLabel = tk.Label(top)
        self.BusinessPhoneLabel.place(relx=0.45, rely=0.889, height=26
                , width=112)
        self.BusinessPhoneLabel.configure(activebackground="#f9f9f9")
        self.BusinessPhoneLabel.configure(activeforeground="black")
        self.BusinessPhoneLabel.configure(background="#d9d9d9")
        self.BusinessPhoneLabel.configure(disabledforeground="#a3a3a3")
        self.BusinessPhoneLabel.configure(foreground="#000000")
        self.BusinessPhoneLabel.configure(highlightbackground="#d9d9d9")
        self.BusinessPhoneLabel.configure(highlightcolor="black")
        self.BusinessPhoneLabel.configure(text='''Contact phone''')

        self.TicketValueEntry = tk.Entry(top)
        self.TicketValueEntry.place(relx=0.183, rely=0.333, height=24
                , relwidth=0.173)
        self.TicketValueEntry.configure(background="white")
        self.TicketValueEntry.configure(disabledforeground="#a3a3a3")
        self.TicketValueEntry.configure(font="TkFixedFont")
        self.TicketValueEntry.configure(foreground="#000000")
        self.TicketValueEntry.configure(highlightbackground="#d9d9d9")
        self.TicketValueEntry.configure(highlightcolor="black")
        self.TicketValueEntry.configure(insertbackground="black")
        self.TicketValueEntry.configure(selectbackground="blue")
        self.TicketValueEntry.configure(selectforeground="white")

        self.PostedEventsButton = tk.Button(top)
        self.PostedEventsButton.place(relx=0.433, rely=0.089, height=73
                , width=146)
        self.PostedEventsButton.configure(activebackground="#ececec")
        self.PostedEventsButton.configure(activeforeground="#000000")
        self.PostedEventsButton.configure(background="#ff0000")
        self.PostedEventsButton.configure(disabledforeground="#a3a3a3")
        self.PostedEventsButton.configure(foreground="#000000")
        self.PostedEventsButton.configure(highlightbackground="#d9d9d9")
        self.PostedEventsButton.configure(highlightcolor="black")
        self.PostedEventsButton.configure(pady="0")
        self.PostedEventsButton.configure(text='''Display PostedEvents''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.183, rely=0.111, height=24, relwidth=0.207)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.EventDescriptioLabel = tk.Label(top)
        self.EventDescriptioLabel.place(relx=0.017, rely=0.111, height=26
                , width=82)
        self.EventDescriptioLabel.configure(background="#d9d9d9")
        self.EventDescriptioLabel.configure(disabledforeground="#a3a3a3")
        self.EventDescriptioLabel.configure(foreground="#000000")
        self.EventDescriptioLabel.configure(text='''Event's Name''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





